language: node_js
after_success: npm run coverage && cat ./coverage/lcov.info | coveralls 
script:
  - npm run pretest
  - npm run $CMD
cache:
  npm: false
matrix:
  include:
    - node_js: "0.10"
      env: CMD=test-node
    - node_js: "0.12"
      env: CMD=test-node
    - node_js: 4
      env: CMD=test-node
    - node_js: 6
      env: CMD=test-node
    - node_js: 8
      env: CMD=test-node
    - node_js: 10
      env: CMD=test-node
    - node_js: 10
      env: CMD=test-262
    - node_js: 10
      env: CMD=test-browser
  fast_finish: true
sudo: false
